server:
  port: ${SERVER_PORT:8080}

spring:
  r2dbc:
    name: rinha-datasource
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jackson:
    deserialization:
      accept-float-as-int: false