version: "3.5"
services:
  api1: &api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    hostname: api1
    container_name: api1-rb
    depends_on:
      - postgres
    network_mode: host
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api2
    container_name: api2-rb
    environment:
      SERVER_PORT: 8081

  nginx:
    image: nginx:alpine
    container_name: nginx-rb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  postgres:
    image: postgres:16.2
    container_name: postgres-rb
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    network_mode: host

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf

    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "300MB"

volumes:
  postgres-data: